### PR TITLE
fix(route information popup): make text in route info not split mid-word

### LINKED ISSUE #277: Route duration wraps inconveniently
Requesting a route on a fresh install caused the route Duration to be wrapped such that it was misinterpreted:
Screenshot 2022-11-29 at 12-12-50 ORS Maps

It should read: ` 21 hour(s) 45 min 41 s` but was read as `in 41s` and interpreted as "the route was calculated in 41 s"

### PR DESCRIPTION
**Pull request by koebi**
Previously divs and floating features were used for the layout of the popups of route information. Though this provided suitable display normally, the size of the leaflet popup is based on the size of the div. When the icon for the profile is floated, this moves the text but doesn't change the size of the underlying div, which meant that the text got wrapped into new lines. In this commit, the divs have been replaced with spans using inline-block display so that the parent div resizes as expected.

fix #277

### CODE REVIEW

**Review by MichaelsJP — DISMISSED** [review]

File: src/fragments/map-view/components/ors-l-polyline/ors-l-polyline.js [hunk 1]
```diff
@@ -203,11 +203,9 @@ export default {
         }
         if (tooltipIcon) {
           let tooltip = `
-          <div>
-            <div style='min-width:30px;width:20%;height:50px;float:left'>
-              <span style='${iconStyle}' class="material-icons">${tooltipIcon}</span>
-            </div>
-            <div style='min-width:180px'>${tooltipInnerContent}</div>
+          <div style='vertical-align: middle'>
```
Comment (koebi) [inline src/fragments/map-view/components/ors-l-polyline/ors-l-polyline.js:206]: `vertical-align: middle` is only used on inline elements, not block elements.
I assume the idea here was to align contents of this div vertically - this should be on the `span`s then.

**Review by MichaelsJP — DISMISSED** [review]

**Review by TheGreatRefrigerator — APPROVED** [review]
Works on jakobs machine
