### PR TITLE
fix: add stop by dragging route

### LINKED ISSUE #439: drag from route not working anymore
grafik
Dragging a new point from a route is not generating a new waypoint, but throws an exception (console)

### PR DESCRIPTION
**Pull request by EmmaHegarty**
fixes #439

### CODE REVIEW

File: src/fragments/forms/map-form/components/place-and-directions/places-and-directions.js [hunk 1]
```diff
@@ -463,7 +463,7 @@ export default {
         // In the other cases, we have to 'inject' a route point between the exiting points
         // To do that we add a place input, set its coordinates, and then
         // we change the app url so that the route will be recalculated
-        const injectedIndex = this.injectPlaceAndReturnIndex(data.latLng, closestPlaceIndex)
+        const injectedIndex = this.injectPlaceAndReturnIndex(data.latlng, closestPlaceIndex)
```
Comment (TheGreatRefrigerator) [inline src/fragments/forms/map-form/components/place-and-directions/places-and-directions.js:466]: .latlng is only passed on drags from route geometry, as it uses the native leaflet event directly passed as data.
To not break functionality normal rout stop adding, we need to expose .latLng from .latlng if it's not there

**Review by TheGreatRefrigerator — APPROVED** [review]
